const EMBEDDED_FRAUD_DATA = {
  "geo_data": [
    {
      "orden": "465676178_O_CO_23",
      "external_id": "1113691108",
      "tecnico": "BRAYAN STEVEN GUERRON TORRES",
      "fecha": "2026-02-25",
      "inicio": "15:08",
      "fin": "16:13",
      "cliente": "WALTER LOZANO MARTINEZ",
      "direccion": "Calle: CR 15A Placa: 47D-48 Apto: PI1-IN101 Com: PAL Div: RVA",
      "ciudad": "PALMIRA",
      "nodo": "PBU",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.54421,
      "longitud": -76.28794,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "PDV",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "ANDREA CATALINA DE LA",
      "codigo_asesor": "298758",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 65,
      "tiempo_viaje_minutos": 29,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466199931_O_CO_7",
      "external_id": "1061701152",
      "tecnico": "DIDIER ENRIQUE PEREZ SARRIA",
      "fecha": "2026-03-06",
      "inicio": "14:39",
      "fin": "15:00",
      "cliente": "MILTON AUG MORALES",
      "direccion": "Calle: CL 32NORTE Placa: 8-142 Apto:  PISO2 Com: POP Div: RVA",
      "ciudad": "POPAYAN",
      "nodo": "CB3",
      "zona": 507572,
      "regional": "RVA",
      "latitud": 2.46458,
      "longitud": -76.58827,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "ANDRES MAURICIO MONTER",
      "codigo_asesor": "3215566",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "EN INCUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "26",
      "duracion_minutos": 21,
      "tiempo_viaje_minutos": 25,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "466199931_O_CO_7",
      "external_id": "1061701152",
      "tecnico": "DIDIER ENRIQUE PEREZ SARRIA",
      "fecha": "2026-03-05",
      "inicio": "14:28",
      "fin": "15:39",
      "cliente": "MILTON AUG MORALES TELLO",
      "direccion": "Calle: CL 32NORTE Placa: 8-142 Apto: PISO2 Com: POP Div: RVA",
      "ciudad": "POPAYAN",
      "nodo": "CB3",
      "zona": 507572,
      "regional": "RVA",
      "latitud": 2.46458,
      "longitud": -76.58827,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "ANDRES MAURICIO MONTER",
      "codigo_asesor": "3215566",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 71,
      "tiempo_viaje_minutos": 32,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "466055685_O_CO_7",
      "external_id": "1111540235",
      "tecnico": "YEINEY ALEXIS RIVERA MENESES",
      "fecha": "2026-03-04",
      "inicio": "07:45",
      "fin": "10:19",
      "cliente": "RIGOBERTO CAMPOO-",
      "direccion": "Calle: CR 100OESTE Placa: 1B-12 Apto:  502 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "ASE2F",
      "zona": 508584,
      "regional": "RVA",
      "latitud": 3.37223,
      "longitud": -76.5557,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "ANGEL DUBAN MEDINA GUE",
      "codigo_asesor": "16949707",
      "confirmacion": "no",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "EN INCUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "13",
      "duracion_minutos": 154,
      "tiempo_viaje_minutos": 4,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466055828_O_CO_7",
      "external_id": "1075238735",
      "tecnico": "JORGE LEONARDO REYES CASTILLO",
      "fecha": "2026-03-04",
      "inicio": "12:01",
      "fin": "12:54",
      "cliente": "JHOJAN AND CHAVEZ RODRIGUEZ",
      "direccion": "Calle: CL 18 Placa: 53-46 Apto: PISO1 Com: NEI Div: RCE",
      "ciudad": "NEIVA",
      "nodo": "PMS1",
      "zona": 506564,
      "regional": "RCE",
      "latitud": 2.94087,
      "longitud": -75.24624,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "ARDILA VAZQUEZ ALIX AL",
      "codigo_asesor": "26433289",
      "confirmacion": "si",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 53,
      "tiempo_viaje_minutos": 7,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465171981_O_CO_7",
      "external_id": "1112299805",
      "tecnico": "MILTON ANDRES AGUDELO RAMIREZ",
      "fecha": "2026-02-20",
      "inicio": "15:51",
      "fin": "18:13",
      "cliente": "MARTHA LIL RODRiGUEZ SANCHEZ",
      "direccion": "Calle: CL 22A Placa: 15-12 Apto: PISO3 Com: BUG Div: RVA",
      "ciudad": "BUGA",
      "nodo": "D2B",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.91341,
      "longitud": -76.29744,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "ARLEX ADEY PALACIOS LO",
      "codigo_asesor": "7585025",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 142,
      "tiempo_viaje_minutos": 15,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465732324_O_CO_7",
      "external_id": "1070606593",
      "tecnico": "JESUS ALFREDO RODRIGUEZ MORA",
      "fecha": "2026-02-26",
      "inicio": "10:26",
      "fin": "11:36",
      "cliente": "LUZ MARIAN LOZANO ALVAREZ",
      "direccion": "Calle: QUINTAS DEFLANDES Placa: MZ35-C7 Apto: PI1-102 Com: FLA Div: RCE",
      "ciudad": "FLANDES",
      "nodo": "QTN",
      "zona": 506561,
      "regional": "RCE",
      "latitud": 4.27734,
      "longitud": -74.81586,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "ARLEX ADEY PALACIOS LO",
      "codigo_asesor": "7585025",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 70,
      "tiempo_viaje_minutos": 7,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "466342640_O_CO_761",
      "external_id": "1006009171",
      "tecnico": "ANDRES FELIPE VICUA GARCIA",
      "fecha": "2026-03-07",
      "inicio": "17:27",
      "fin": "18:39",
      "cliente": "CARLOS ELI MARTINEZ",
      "direccion": "Calle: CR 42C Placa: 48-75 Apto:  PI1-101 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "OBFL10",
      "zona": 508584,
      "regional": "RVA",
      "latitud": 3.40386,
      "longitud": -76.50768,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "AVILA ROMERO NILSE DIO",
      "codigo_asesor": "44169718",
      "confirmacion": "si",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "EN INCUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "5",
      "duracion_minutos": 72,
      "tiempo_viaje_minutos": 3,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466204260_O_CO_7",
      "external_id": "1002958746",
      "tecnico": "RICHAR ALIRIO PEA ZUIGA",
      "fecha": "2026-03-05",
      "inicio": "17:52",
      "fin": "18:58",
      "cliente": "LUIS EDUAR LOPEZ GUTIERREZ",
      "direccion": "Calle: CR 9 TORRE A Placa: 17N-47 Apto: 302 Com: POP Div: RVA",
      "ciudad": "POPAYAN",
      "nodo": "4SN",
      "zona": 507572,
      "regional": "RVA",
      "latitud": 2.45464,
      "longitud": -76.59865,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "DIGITAL",
      "canal2": "ECOMMERCE ASISTIDO",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "BARRERA RODRIGUEZ MAN",
      "codigo_asesor": "32412323",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 66,
      "tiempo_viaje_minutos": 43,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464898468_O_CO_761",
      "external_id": "1068972003",
      "tecnico": "CARLOS ADRIAN ROJAS CRUZ",
      "fecha": "2026-02-14",
      "inicio": "14:35",
      "fin": "15:16",
      "cliente": "LUIS CARLO BLANDON ACEVEDO",
      "direccion": "Calle: CL 37 Placa: 1BN-76 Apto: PISO2 Com: CGO Div: REC",
      "ciudad": "CARTAGO",
      "nodo": "CT03",
      "zona": 507578,
      "regional": "REC",
      "latitud": 4.76154,
      "longitud": -75.93439,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "BOLIVAR PULGARIN YESSI",
      "codigo_asesor": "12780923",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 41,
      "tiempo_viaje_minutos": 25,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Luis carlos Blandon Acevedo"
    },
    {
      "orden": "466053908_O_CO_7",
      "external_id": "719199",
      "tecnico": "JOSE ADOLFO TORRES TORRES",
      "fecha": "2026-03-05",
      "inicio": "07:17",
      "fin": "08:57",
      "cliente": "JHON EDINS BOTINA",
      "direccion": "Calle: AV 4AOESTE Placa: 19-108 Apto:  PI1-102 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "AIA",
      "zona": 508584,
      "regional": "RVA",
      "latitud": 3.45252,
      "longitud": -76.56076,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "BUITRAGO GIRALDO VALEN",
      "codigo_asesor": "92771397",
      "confirmacion": "si",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 36,
      "sla_cumplimiento": "NODATA",
      "duracion_minutos": 100,
      "tiempo_viaje_minutos": 7,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464785224_O_CO_761",
      "external_id": "1107077888",
      "tecnico": "IJAJI SAMBONI EYSON FERNANDO",
      "fecha": "2026-02-12",
      "inicio": "13:41",
      "fin": "14:11",
      "cliente": "JOSEPH MAN FORIS CAICEDO",
      "direccion": "Calle: CR 43B Placa: 48A-30 Apto: PI1-101 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "OBFL08",
      "zona": 508584,
      "regional": "RVA",
      "latitud": 3.40235,
      "longitud": -76.50904,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "AGENTES",
      "canal2": "PDV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "CARDONA ZAPATA LUZ ARG",
      "codigo_asesor": "43652192",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 30,
      "tiempo_viaje_minutos": 61,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "JOSEPH MANUEL FORIS CAICEDO"
    },
    {
      "orden": "466384228_O_CO_761",
      "external_id": "11938207",
      "tecnico": "WILNER YESID RIASCOS MOSQUERA",
      "fecha": "2026-03-09",
      "inicio": "13:05",
      "fin": "13:05",
      "cliente": "ROSA MARIA MARTINEZ CRUZ",
      "direccion": "Calle: CL 47CNORTE Placa: 2AN-65 Apto: CASA Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "OBFM58",
      "zona": 508582,
      "regional": "RVA",
      "latitud": 3.47931,
      "longitud": -76.51211,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "DIGITAL",
      "canal2": "ECOMMERCE ASISTIDO",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "CASTILLO GARCIA JOHANN",
      "codigo_asesor": "14659626",
      "confirmacion": "si",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Completar visita sistema",
      "despac_gestion": "Visita completada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 0,
      "tiempo_viaje_minutos": 0,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466462967_O_CO_761",
      "external_id": "10307215",
      "tecnico": "EVILEY ALBERTO SERNA OROZCO",
      "fecha": "2026-03-09",
      "inicio": "15:48",
      "fin": "16:27",
      "cliente": "ANTONIO DU HERNANDEZ QUIBONO",
      "direccion": "Calle: CL 29ANORTE Placa: 7A-09 Apto: CASA Com: POP Div: RVA",
      "ciudad": "POPAYAN",
      "nodo": "OBFO39",
      "zona": 507572,
      "regional": "RVA",
      "latitud": 2.46163,
      "longitud": -76.58711,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "CHITOYEISON EDUARDO",
      "codigo_asesor": "60988984",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 39,
      "tiempo_viaje_minutos": 41,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "466315586_O_CO_23",
      "external_id": "1113519426",
      "tecnico": "DIEGO FERNANDO LOPEZ ALTAMIRANO",
      "fecha": "2026-03-07",
      "inicio": "08:24",
      "fin": "09:51",
      "cliente": "JHOINER FORI",
      "direccion": "Calle: CL 55A Placa: 42B-57 Apto: PISO1 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "F4M1",
      "zona": 508584,
      "regional": "RVA",
      "latitud": 3.39966,
      "longitud": -76.50363,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "DIEGO ANDRES SOTO MART",
      "codigo_asesor": "34399048",
      "confirmacion": "si",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 87,
      "tiempo_viaje_minutos": 29,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464883796_O_CO_7",
      "external_id": "1130644042",
      "tecnico": "JAIME IBARGUEN ANGULO",
      "fecha": "2026-02-17",
      "inicio": "16:22",
      "fin": "18:50",
      "cliente": "LILIANA MA BUENO",
      "direccion": "Calle: CL 31A Placa: 33B-11 Apto:  PI1-102 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "L3S",
      "zona": 508582,
      "regional": "RVA",
      "latitud": 3.42259,
      "longitud": -76.51298,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "EDWIN ANDRES HERNANDEZ",
      "codigo_asesor": "21828686",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Completar visita sistema",
      "despac_gestion": "Visita completada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 148,
      "tiempo_viaje_minutos": 33,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465127332_O_CO_761",
      "external_id": "1112100607",
      "tecnico": "JORGE LUIS HENAO SALAZAR",
      "fecha": "2026-02-19",
      "inicio": "17:06",
      "fin": "18:15",
      "cliente": "MARiA FELI MOSQUERA",
      "direccion": "Calle: DG 1A Placa: T1-38 Apto: PISO2 Com: CGO Div: REC",
      "ciudad": "CARTAGO",
      "nodo": "CTDE15",
      "zona": 507578,
      "regional": "REC",
      "latitud": 4.75579,
      "longitud": -75.90071,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "ERIKA PAOLA ESPINOSA V",
      "codigo_asesor": "6294145",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 69,
      "tiempo_viaje_minutos": 0,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "464527565_O_CO_23",
      "external_id": "1061541436",
      "tecnico": "JHEFRY GABRIEL DUQUE MACA",
      "fecha": "2026-02-10",
      "inicio": "07:05",
      "fin": "08:23",
      "cliente": "LEANDRO CALDERON VELASCO",
      "direccion": "Calle: CL 72A Placa: 27A-04 Apto: PI1-101 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "CPE1",
      "zona": 508582,
      "regional": "RVA",
      "latitud": 3.43028,
      "longitud": -76.49539,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "ESTEBAN CALLE CHAVARRI",
      "codigo_asesor": "10066299",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 78,
      "tiempo_viaje_minutos": 12,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466078975_O_CO_23",
      "external_id": "1075270238",
      "tecnico": "JAVIER DELGADO CEDEO",
      "fecha": "2026-03-04",
      "inicio": "14:52",
      "fin": "16:46",
      "cliente": "EDNA VIOLE ZEA CHAVARRO",
      "direccion": "Calle: CL 31 Placa: 6-47 Apto: PI2-201 Com: NEI Div: RCE",
      "ciudad": "NEIVA",
      "nodo": "TM1",
      "zona": 506564,
      "regional": "RCE",
      "latitud": 2.94576,
      "longitud": -75.29134,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "FAVIO VEGA DOCTOR",
      "codigo_asesor": "7699003",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 114,
      "tiempo_viaje_minutos": 39,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464838439_O_CO_12",
      "external_id": "1112229027",
      "tecnico": "ORTIZ SALAZAR JEAN CARLOS",
      "fecha": "2026-02-14",
      "inicio": "08:02",
      "fin": "08:46",
      "cliente": "JANER HURTADO",
      "direccion": "Calle: CL 10 Placa: 13A-07 Apto: PI1-LC101 Com: FLR Div: RVA",
      "ciudad": "FLORIDA",
      "nodo": "KAN2F",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.32337,
      "longitud": -76.23116,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Pymes",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Pymes",
      "asesor": "FLOREZ CARLOS ARTURO",
      "codigo_asesor": "21419971",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 44,
      "tiempo_viaje_minutos": 1,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465661452_O_CO_7",
      "external_id": "1070606593",
      "tecnico": "JESUS ALFREDO RODRIGUEZ MORA",
      "fecha": "2026-02-25",
      "inicio": "14:23",
      "fin": "15:20",
      "cliente": "JASMITH ROMERO",
      "direccion": "Calle: CR 5 Placa: 10-28 Apto:  PISO1 Com: FLA Div: RCE",
      "ciudad": "FLANDES",
      "nodo": "QTO3F",
      "zona": 506561,
      "regional": "RCE",
      "latitud": 4.28861,
      "longitud": -74.81186,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "GOMEZ VILLANUEVA HAROL",
      "codigo_asesor": "11205789",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 57,
      "tiempo_viaje_minutos": 9,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "466189955_O_CO_1381",
      "external_id": "1077421194",
      "tecnico": "HERBIN ARLEY MURILLO MOSQUERA",
      "fecha": "2026-03-07",
      "inicio": "08:53",
      "fin": "09:18",
      "cliente": "AURA CECIL MUNOZ MARTINEZ",
      "direccion": "Calle: CR 1B3 Placa: 61A-31 Apto: CASA Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "B2Q3F",
      "zona": 508582,
      "regional": "RVA",
      "latitud": 3.47613,
      "longitud": -76.49524,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "TELEFONICO SERVICIO",
      "canal2": "SAC",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "BROWNFIELD",
      "asesor": "GONZALEZ CESPEDES JUAN",
      "codigo_asesor": "1060730",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 25,
      "tiempo_viaje_minutos": 27,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464834143_O_CO_761",
      "external_id": "1193520340",
      "tecnico": "JHON JAIRO GARCIA TORRES",
      "fecha": "2026-02-17",
      "inicio": "13:00",
      "fin": "13:21",
      "cliente": "SANDRA MIL MURILLO",
      "direccion": "Calle: CL 57A Placa: 53-40 Apto:  CASA Com: SEV Div: RVA",
      "ciudad": "SEVILLA",
      "nodo": "SEVIG7",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 4.2702,
      "longitud": -75.93624,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK IN BOUND",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "GUZMAN VELA SEBASTIAN",
      "codigo_asesor": "1051831",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 21,
      "tiempo_viaje_minutos": 0,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464834143_O_CO_761",
      "external_id": "1144163538",
      "tecnico": "CARLOS FABIAN LEIVA CRUZ",
      "fecha": "2026-02-16",
      "inicio": "13:17",
      "fin": "15:11",
      "cliente": "SANDRA MIL MURILLO",
      "direccion": "Calle: CL 57A Placa: 53-40 Apto:  CASA Com: SEV Div: RVA",
      "ciudad": "SEVILLA",
      "nodo": "SEVIG7",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 4.2702,
      "longitud": -75.93624,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK IN BOUND",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "GUZMAN VELA SEBASTIAN",
      "codigo_asesor": "1051831",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 114,
      "tiempo_viaje_minutos": 6,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "466175756_O_CO_23",
      "external_id": "1144175992",
      "tecnico": "JEFERSON ANDRES MORALES CIFUENTES",
      "fecha": "2026-03-05",
      "inicio": "12:33",
      "fin": "13:18",
      "cliente": "ALVARO JOS MINA ZAPATA",
      "direccion": "Calle: CL 49 TORRE 1 Placa: 112-25 Apto: 403 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "NVE1",
      "zona": 508584,
      "regional": "RVA",
      "latitud": 3.35569,
      "longitud": -76.51485,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "HAIDER DAVID MEDINA CA",
      "codigo_asesor": "39426478",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 45,
      "tiempo_viaje_minutos": 8,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "466279090_O_CO_23",
      "external_id": "10754848",
      "tecnico": "ALEX JOVANNY VICTORIA PECHENE",
      "fecha": "2026-03-07",
      "inicio": "16:00",
      "fin": "16:29",
      "cliente": "DARLYN SLE LIEBANO ORTIZ",
      "direccion": "Calle: CL 36 Placa: 13-03 Apto: PI2-201 Com: PAL Div: RVA",
      "ciudad": "PALMIRA",
      "nodo": "4SP",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.53235,
      "longitud": -76.28574,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "HERNANDEZ PERALTA JONA",
      "codigo_asesor": "14697794",
      "confirmacion": "si",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 29,
      "tiempo_viaje_minutos": 14,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465113594_O_CO_7",
      "external_id": "4668764",
      "tecnico": "ARY ROBERTO GOMEZ GUAMPE",
      "fecha": "2026-02-19",
      "inicio": "16:24",
      "fin": "17:43",
      "cliente": "GLORIA ESP VICTORIAA",
      "direccion": "Calle: CR 27 Placa: 16B-06 Apto: PISO1 Com: POP Div: RVA",
      "ciudad": "POPAYAN",
      "nodo": "VGE",
      "zona": 507572,
      "regional": "RVA",
      "latitud": 2.44524,
      "longitud": -76.62579,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "AGENTES",
      "canal2": "PDV",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "HOMEN BURBANO CLAUDIA",
      "codigo_asesor": "61751151",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 79,
      "tiempo_viaje_minutos": 57,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "464787498_O_CO_23",
      "external_id": "1085247057",
      "tecnico": "JAIME EDWIN CAMPAA",
      "fecha": "2026-02-13",
      "inicio": "10:29",
      "fin": "11:18",
      "cliente": "YAMILE FER RIVERA",
      "direccion": "Calle: LA MINGA Placa: MZ21-C12 Apto:  PISO2 Com: PAS Div: RVA",
      "ciudad": "PASTO",
      "nodo": "TOG3B",
      "zona": 507573,
      "regional": "RVA",
      "latitud": null,
      "longitud": null,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK IN BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "JAIR PALACIO NIEVES",
      "codigo_asesor": "2024061",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 49,
      "tiempo_viaje_minutos": 48,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "464555634_O_CO_23",
      "external_id": "1130653107",
      "tecnico": "MONCAYO EDDIER MORA",
      "fecha": "2026-02-10",
      "inicio": "10:50",
      "fin": "11:47",
      "cliente": "SHIRLEY LI MAMIAN GOMEZ",
      "direccion": "Calle: CR 42A1 Placa: 38-82 Apto: CASA Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "UVU",
      "zona": 508584,
      "regional": "RVA",
      "latitud": 3.41161,
      "longitud": -76.51332,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "JANIRIA BERNAL JIMENEZ",
      "codigo_asesor": "29993967",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 57,
      "tiempo_viaje_minutos": 14,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464934946_O_CO_7",
      "external_id": "1070606593",
      "tecnico": "JESUS ALFREDO RODRIGUEZ MORA",
      "fecha": "2026-02-16",
      "inicio": "09:50",
      "fin": "10:21",
      "cliente": "INDER IGNA IBANEZ",
      "direccion": "Calle: CR 11 Placa: 21-90 Apto:  PI1-101 Com: ESP Div: RCE",
      "ciudad": "ESPINAL",
      "nodo": "ESV",
      "zona": 506561,
      "regional": "RCE",
      "latitud": 4.14186,
      "longitud": -74.89393,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "JEFERSON RODRIGUEZ ROM",
      "codigo_asesor": "69925728",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "EN INCUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 31,
      "tiempo_viaje_minutos": 21,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "464824391_O_CO_23",
      "external_id": "1061719966",
      "tecnico": "DILERMANDO ULCUE ACHIPIZ",
      "fecha": "2026-02-14",
      "inicio": "16:58",
      "fin": "18:13",
      "cliente": "CARMELA DELGADO CARVAJAL",
      "direccion": "Calle: CR 12 Placa: 31-59 Apto: PI1-101 Com: POP Div: RVA",
      "ciudad": "POPAYAN",
      "nodo": "LMV1",
      "zona": 507572,
      "regional": "RVA",
      "latitud": 2.42284,
      "longitud": -76.61532,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "JHOANA PAOLA VARON BE",
      "codigo_asesor": "998039",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 75,
      "tiempo_viaje_minutos": 17,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "TT"
    },
    {
      "orden": "464767521_O_CO_7",
      "external_id": "1114837203",
      "tecnico": "ANGEL HERRERA GUZMAN LUIS",
      "fecha": "2026-02-16",
      "inicio": "09:28",
      "fin": "09:59",
      "cliente": "MARIA YUSL SANCHEZ",
      "direccion": "Calle: CL 55A Placa: 41-12 Apto:  PI1-101 Com: PAL Div: RVA",
      "ciudad": "PALMIRA",
      "nodo": "OS3",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.54705,
      "longitud": -76.31233,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "JHONN JAIRO ORTEGA PER",
      "codigo_asesor": "59907987",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 31,
      "tiempo_viaje_minutos": 17,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "464892202_O_CO_7",
      "external_id": "11220981",
      "tecnico": "HECTOR VICENTE MARQUEZ BARRETO",
      "fecha": "2026-02-14",
      "inicio": "10:36",
      "fin": "11:22",
      "cliente": "JOSE AGUST LUNA",
      "direccion": "Calle: CONDOMINIO PAKISTAN1   Placa: 0-00 Apto:  CASA71 Com: FLA Div: RCE",
      "ciudad": "FLANDES",
      "nodo": "PAK",
      "zona": 506561,
      "regional": "RCE",
      "latitud": 4.2677,
      "longitud": -74.81443,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "PDV",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "JOAN MAURICIO GARCIA Q",
      "codigo_asesor": "17165567",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 46,
      "tiempo_viaje_minutos": 6,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "466055628_O_CO_23",
      "external_id": "16897444",
      "tecnico": "ZAMBRANO ALEXANDER MUNOZ",
      "fecha": "2026-03-04",
      "inicio": "12:03",
      "fin": "13:05",
      "cliente": "DARLYN SLE LIEVANO ORTIZ",
      "direccion": "Calle: CL 36 Placa: 13-03 Apto: PI2-201 Com: PAL Div: RVA",
      "ciudad": "PALMIRA",
      "nodo": "4SP",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.53235,
      "longitud": -76.28574,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "JOHANA ROSERO PERENGUE",
      "codigo_asesor": "13631959",
      "confirmacion": "si",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 62,
      "tiempo_viaje_minutos": 32,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465963361_O_CO_7",
      "external_id": "10754848",
      "tecnico": "ALEX JOVANNY VICTORIA PECHENE",
      "fecha": "2026-03-02",
      "inicio": "14:01",
      "fin": "15:52",
      "cliente": "MARIA LAUR ARAGON",
      "direccion": "Calle: CL 35A Placa: 9-61 Apto:  PI1-102 Com: PAL Div: RVA",
      "ciudad": "PALMIRA",
      "nodo": "JOS",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.5314,
      "longitud": -76.2825,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "JOHANA ROSERO PERENGUE",
      "codigo_asesor": "13631959",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "EN INCUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "2",
      "duracion_minutos": 111,
      "tiempo_viaje_minutos": 26,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465076685_O_CO_23",
      "external_id": "1113638086",
      "tecnico": "MERA GIOVANNY TORRES",
      "fecha": "2026-02-19",
      "inicio": "15:16",
      "fin": "17:26",
      "cliente": "SANDRA MIL RUIZ",
      "direccion": "Calle: CL 54A Placa: 44-04 Apto:  PISO2 Com: PAL Div: RVA",
      "ciudad": "PALMIRA",
      "nodo": "OS4",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.54664,
      "longitud": -76.31572,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "JOHANA ROSERO PERENGUE",
      "codigo_asesor": "13631959",
      "confirmacion": "no",
      "confir_resultado": "REPROGRAMADA",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 130,
      "tiempo_viaje_minutos": 43,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465707661_O_CO_23",
      "external_id": "1118364131",
      "tecnico": "JOEL ANDREY QUIROGA SANCHEZ",
      "fecha": "2026-02-25",
      "inicio": "16:35",
      "fin": "17:44",
      "cliente": "JOSE ANGEL GUAYARA",
      "direccion": "Calle: CR 9 Placa: 20-03 Apto:  CASA Com: FLE Div: RCE",
      "ciudad": "FLORENCIA",
      "nodo": "HPI",
      "zona": 506564,
      "regional": "RCE",
      "latitud": 1.61984,
      "longitud": -75.61236,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "JOSE LUIS OLARTE NOREN",
      "codigo_asesor": "1726",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "EN INCUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "1",
      "duracion_minutos": 69,
      "tiempo_viaje_minutos": 12,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465797366_O_CO_761",
      "external_id": "1004134308",
      "tecnico": "JOHNNY RODRIGO DE LA CRUZ DIAZ",
      "fecha": "2026-02-27",
      "inicio": "11:13",
      "fin": "13:41",
      "cliente": "JONATHAN BOLANOS INSUASTY",
      "direccion": "Calle: LAS VIOLETAS2 Placa: MZB-C1 Apto: CASA Com: PAS Div: RVA",
      "ciudad": "PASTO",
      "nodo": "OBFJ39",
      "zona": 507573,
      "regional": "RVA",
      "latitud": null,
      "longitud": null,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "KATHERIN DAZA IBARRA",
      "codigo_asesor": "85283041",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 148,
      "tiempo_viaje_minutos": 35,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "466197423_O_CO_7",
      "external_id": "1006502950",
      "tecnico": "JANYER VALENZUELA GARZON",
      "fecha": "2026-03-05",
      "inicio": "14:02",
      "fin": "15:38",
      "cliente": "WILFREDO ESCARPETA CARVAJAL",
      "direccion": "Calle: TR 5B Placa: 11-58 Apto: CASA Com: FLE Div: RCE",
      "ciudad": "FLORENCIA",
      "nodo": "XX1",
      "zona": 506564,
      "regional": "RCE",
      "latitud": 1.61164,
      "longitud": -75.60822,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK IN BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "LEON RIANO JOHAN SAMUE",
      "codigo_asesor": "14267828",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 96,
      "tiempo_viaje_minutos": 8,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "464638513_O_CO_7",
      "external_id": "1113638086",
      "tecnico": "MERA GIOVANNY TORRES",
      "fecha": "2026-02-11",
      "inicio": "15:10",
      "fin": "15:43",
      "cliente": "BEATRIZ MURILLO",
      "direccion": "Calle: CL 58B Placa: 39-37 Apto:  PI1-101 Com: PAL Div: RVA",
      "ciudad": "PALMIRA",
      "nodo": "OS2",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.54879,
      "longitud": -76.31053,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "PDV",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "LUIS ADOLFO VALENCIA R",
      "codigo_asesor": "11789169",
      "confirmacion": "si",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 33,
      "tiempo_viaje_minutos": 3,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466039842_O_CO_7",
      "external_id": "1081182143",
      "tecnico": "SANTIAGO ACUA LOSADA",
      "fecha": "2026-03-04",
      "inicio": "07:25",
      "fin": "08:19",
      "cliente": "ENI GUTIERREZ",
      "direccion": "Calle: CL 3A Placa: 34-58 Apto:  PI1-IN1 Com: NEI Div: RCE",
      "ciudad": "NEIVA",
      "nodo": "SPU1",
      "zona": 506564,
      "regional": "RCE",
      "latitud": 2.92611,
      "longitud": -75.26306,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "LUIS EDUARDO VILLAFANE",
      "codigo_asesor": "31644135",
      "confirmacion": "si",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 54,
      "tiempo_viaje_minutos": 27,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466039842_O_CO_7",
      "external_id": "1075247468",
      "tecnico": "FREDDY AVILES SANCHEZ",
      "fecha": "2026-03-03",
      "inicio": "16:01",
      "fin": "17:58",
      "cliente": "ENI GUTIERREZ HERNANDEZ",
      "direccion": "Calle: CL 3A Placa: 34-58 Apto: PI1-IN1 Com: NEI Div: RCE",
      "ciudad": "NEIVA",
      "nodo": "SPU1",
      "zona": 506564,
      "regional": "RCE",
      "latitud": 2.92611,
      "longitud": -75.26306,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "LUIS EDUARDO VILLAFANE",
      "codigo_asesor": "31644135",
      "confirmacion": "si",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 117,
      "tiempo_viaje_minutos": 12,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466074185_O_CO_761",
      "external_id": "1086279119",
      "tecnico": "OSCAR ALONSO MONTOYA MANRIQUE",
      "fecha": "2026-03-04",
      "inicio": "10:31",
      "fin": "11:15",
      "cliente": "EDGAR QUIROGA BATISTA",
      "direccion": "Calle: CL 34 Placa: 1BN-61 Apto: CASA Com: CGO Div: REC",
      "ciudad": "CARTAGO",
      "nodo": "CT13",
      "zona": 507578,
      "regional": "REC",
      "latitud": 4.76256,
      "longitud": -75.93328,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "MAESTRE BIRRIEL ELISA",
      "codigo_asesor": "527496",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 44,
      "tiempo_viaje_minutos": 0,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465992264_O_CO_761",
      "external_id": "1059706835",
      "tecnico": "SEBASTIAN GUTIERREZ MORALES",
      "fecha": "2026-03-03",
      "inicio": "14:27",
      "fin": "15:28",
      "cliente": "EDGAR QUIROGA BAUTISTA",
      "direccion": "Calle: CL 34 Placa: 1BN-61 Apto: CASA Com: CGO Div: REC",
      "ciudad": "CARTAGO",
      "nodo": "CT13",
      "zona": 507578,
      "regional": "REC",
      "latitud": 4.76256,
      "longitud": -75.93328,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "MAESTRE BIRRIEL ELISA",
      "codigo_asesor": "527496",
      "confirmacion": "si",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 61,
      "tiempo_viaje_minutos": 7,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "NO CONTACTO"
    },
    {
      "orden": "465130428_O_CO_23",
      "external_id": "1112299805",
      "tecnico": "MILTON ANDRES AGUDELO RAMIREZ",
      "fecha": "2026-02-20",
      "inicio": "10:22",
      "fin": "11:17",
      "cliente": "ANGIE ALEJ BALTAN",
      "direccion": "Calle: CR 15B Placa: 31-38 Apto:  PISO2 Com: BUG Div: RVA",
      "ciudad": "BUGA",
      "nodo": "MTN1",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.92005,
      "longitud": -76.29573,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "MARIA CAROLINA PENA RA",
      "codigo_asesor": "31640336",
      "confirmacion": "no",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "EN INCUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "19",
      "duracion_minutos": 55,
      "tiempo_viaje_minutos": 2,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465828876_O_CO_23",
      "external_id": "719199",
      "tecnico": "JOSE ADOLFO TORRES TORRES",
      "fecha": "2026-02-28",
      "inicio": "10:10",
      "fin": "12:13",
      "cliente": "JANETH MAMIAN",
      "direccion": "Calle: CR 26P Placa: 87-04 Apto: PI1-101 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "MQ2",
      "zona": 508582,
      "regional": "RVA",
      "latitud": 3.42595,
      "longitud": -76.4802,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Basica Bi",
      "asesor": "MIGUEL ANGEL LOPEZ ARE",
      "codigo_asesor": "15071076",
      "confirmacion": "si",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 123,
      "tiempo_viaje_minutos": 47,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465793910_O_CO_761",
      "external_id": "1085323870",
      "tecnico": "ANDERSON ALDAIR GUERRERO CHANA",
      "fecha": "2026-02-27",
      "inicio": "11:09",
      "fin": "11:53",
      "cliente": "MONICA VAN DAVILA CAICEDO",
      "direccion": "Calle: CR 22 Placa: 22-14 Apto: 505 Com: PAS Div: RVA",
      "ciudad": "PASTO",
      "nodo": "OBFX36",
      "zona": 507573,
      "regional": "RVA",
      "latitud": 1.21386,
      "longitud": -77.27452,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "MILLER SANTACRUZ NARVA",
      "codigo_asesor": "85298071",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 44,
      "tiempo_viaje_minutos": 28,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465285415_O_CO_761",
      "external_id": "1113529388",
      "tecnico": "ANDERSON ELESVAN VALENCIA AGUIRRE",
      "fecha": "2026-02-24",
      "inicio": "07:32",
      "fin": "09:30",
      "cliente": "DEICY YINE CARDOZO LOZANO",
      "direccion": "Calle: CL 20A Placa: 14-125 Apto: PI1-101 Com: CAN Div: RVA",
      "ciudad": "CANDELARIA",
      "nodo": "OCDIQB",
      "zona": 507578,
      "regional": "RVA",
      "latitud": null,
      "longitud": null,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "MINGAN PERALTA ESTEFAN",
      "codigo_asesor": "12464812",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 118,
      "tiempo_viaje_minutos": 43,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465687278_O_CO_761",
      "external_id": "1002922640",
      "tecnico": "CENEN LEONARDO ESCOBEDO IDROBO",
      "fecha": "2026-02-27",
      "inicio": "14:20",
      "fin": "15:28",
      "cliente": "CAROLINA NAVARRETE SALAZAR",
      "direccion": "Calle: CR 81D Placa: 35-24 Apto: PI1-101 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "OCDJOQ",
      "zona": 508584,
      "regional": "RVA",
      "latitud": 3.38667,
      "longitud": -76.52164,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "MORALES BRITNEY DAYAN",
      "codigo_asesor": "5927609",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 68,
      "tiempo_viaje_minutos": 18,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "CAROLINA NAVARRETE SALAZAR"
    },
    {
      "orden": "465959703_O_CO_761",
      "external_id": "1112100607",
      "tecnico": "JORGE LUIS HENAO SALAZAR",
      "fecha": "2026-03-02",
      "inicio": "14:20",
      "fin": "16:14",
      "cliente": "JESSICA AN MONTOYA CASTRILLON",
      "direccion": "Calle: EL LIMONAR Placa: MZG-C1 Apto: CASA Com: CGO Div: REC",
      "ciudad": "CARTAGO",
      "nodo": "CTCG93",
      "zona": 507578,
      "regional": "REC",
      "latitud": 4.74291,
      "longitud": -75.92473,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "MORALES HERNANDEZ MONI",
      "codigo_asesor": "309774",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 114,
      "tiempo_viaje_minutos": 11,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "464836953_O_CO_7",
      "external_id": "12747298",
      "tecnico": "JORGE ALEXANDER LOPEZ ORTEGA",
      "fecha": "2026-02-14",
      "inicio": "12:41",
      "fin": "13:04",
      "cliente": "ARIANA ARENDS ROBLES",
      "direccion": "Calle: VILLA COLOMBIA Placa: MZC-C7 Apto: PI2-201 Com: PAS Div: RVA",
      "ciudad": "PASTO",
      "nodo": "DIA",
      "zona": 507573,
      "regional": "RVA",
      "latitud": null,
      "longitud": null,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "MOSQUERA AREVALO JOHN",
      "codigo_asesor": "12745688",
      "confirmacion": "si",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "4",
      "duracion_minutos": 23,
      "tiempo_viaje_minutos": 20,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466221197_O_CO_761",
      "external_id": "1061822538",
      "tecnico": "BRAYAN ANDRES PEA ZUIGA",
      "fecha": "2026-03-06",
      "inicio": "07:51",
      "fin": "09:04",
      "cliente": "JESSICA MOLANO",
      "direccion": "Calle: CR 6   Placa: 45N-73 Apto:  PI2-203 Com: POP Div: RVA",
      "ciudad": "POPAYAN",
      "nodo": "OBFO24",
      "zona": 507572,
      "regional": "RVA",
      "latitud": 2.46825,
      "longitud": -76.57873,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "ONATE MEJIA JESUS ALEX",
      "codigo_asesor": "87101846",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 73,
      "tiempo_viaje_minutos": 47,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465165360_O_CO_761",
      "external_id": "1085942474",
      "tecnico": "MARC ANTONY INAGAN PINCHAO",
      "fecha": "2026-02-23",
      "inicio": "08:04",
      "fin": "08:52",
      "cliente": "LUIS FELIP SALCEDO",
      "direccion": "Calle: CL 29 Placa: 6E-53 Apto:  101 Com: IPI Div: RVA",
      "ciudad": "IPIALES",
      "nodo": "IPIPE9",
      "zona": 507573,
      "regional": "RVA",
      "latitud": 0.82757,
      "longitud": -77.65905,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "OSCAR LEONARDO PARRADO",
      "codigo_asesor": "85928553",
      "confirmacion": "no",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 36,
      "sla_cumplimiento": "NODATA",
      "duracion_minutos": 48,
      "tiempo_viaje_minutos": 62,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465165360_O_CO_761",
      "external_id": "1085942474",
      "tecnico": "MARC ANTONY INAGAN PINCHAO",
      "fecha": "2026-02-20",
      "inicio": "16:30",
      "fin": "17:25",
      "cliente": "LUIS FELIP SALCEDO VELASCO",
      "direccion": "Calle: CL 29 Placa: 6E-53 Apto: 101 Com: IPI Div: RVA",
      "ciudad": "IPIALES",
      "nodo": "IPIPE9",
      "zona": 507573,
      "regional": "RVA",
      "latitud": 0.82757,
      "longitud": -77.65905,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "OSCAR LEONARDO PARRADO",
      "codigo_asesor": "85928553",
      "confirmacion": "si",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 55,
      "tiempo_viaje_minutos": 16,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466025766_O_CO_7",
      "external_id": "1061822538",
      "tecnico": "BRAYAN ANDRES PEA ZUIGA",
      "fecha": "2026-03-03",
      "inicio": "15:54",
      "fin": "16:41",
      "cliente": "MARIA JOSE RINCON",
      "direccion": "Calle: CR 30 Placa: 6-86 Apto:  PI1-102 Com: POP Div: RVA",
      "ciudad": "POPAYAN",
      "nodo": "JSE2D",
      "zona": 507572,
      "regional": "RVA",
      "latitud": 2.44794,
      "longitud": -76.62684,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "PENA MORENO DANIEL FEL",
      "codigo_asesor": "10029962",
      "confirmacion": "no",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "EN INCUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "5",
      "duracion_minutos": 47,
      "tiempo_viaje_minutos": 57,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464993367_O_CO_7",
      "external_id": "1075270238",
      "tecnico": "JAVIER DELGADO CEDEO",
      "fecha": "2026-02-17",
      "inicio": "14:21",
      "fin": "15:49",
      "cliente": "AMPARO CHAVARRO PEREZ",
      "direccion": "Calle: CR 13 Placa: 12-47 Apto: PISO1 Com: NEI Div: RCE",
      "ciudad": "NEIVA",
      "nodo": "1LT",
      "zona": 506564,
      "regional": "RCE",
      "latitud": 2.93216,
      "longitud": -75.28245,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "POLANIA MONTERO LUISA",
      "codigo_asesor": "75249868",
      "confirmacion": "si",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Completar visita sistema",
      "despac_gestion": "Visita completada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 88,
      "tiempo_viaje_minutos": 43,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465449332_O_CO_12",
      "external_id": "1113620334",
      "tecnico": "JHON JAIRO MAMIAN VELASCO",
      "fecha": "2026-02-25",
      "inicio": "07:13",
      "fin": "08:39",
      "cliente": "SEBASTIAN BOCANEGRA PANIAGUA",
      "direccion": "Calle: CL 21A Placa: 31-43 Apto: PI1-LC101 Com: PAL Div: RVA",
      "ciudad": "PALMIRA",
      "nodo": "NBN1",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.52025,
      "longitud": -76.30338,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Pymes",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Pymes",
      "asesor": "POTES BEDOYA LUZ AIDEE",
      "codigo_asesor": "66776076",
      "confirmacion": "si",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 86,
      "tiempo_viaje_minutos": 16,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464799786_O_CO_761",
      "external_id": "1061768705",
      "tecnico": "CRISTIAN DANILO URRESTY ORDOEZ",
      "fecha": "2026-02-12",
      "inicio": "16:29",
      "fin": "16:57",
      "cliente": "EMMA CASTRO MEJIA",
      "direccion": "Calle: CR 15N TORRE G Placa: 8N-188 Apto: CS13-PI1 Com: POP Div: RVA",
      "ciudad": "POPAYAN",
      "nodo": "PYBF78",
      "zona": 507572,
      "regional": "RVA",
      "latitud": 2.45796,
      "longitud": -76.60547,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "PULIDO RODRIGUEZ DANIE",
      "codigo_asesor": "468127",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 28,
      "tiempo_viaje_minutos": 38,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465956232_O_CO_761",
      "external_id": "1144163538",
      "tecnico": "CARLOS FABIAN LEIVA CRUZ",
      "fecha": "2026-03-02",
      "inicio": "11:20",
      "fin": "13:49",
      "cliente": "LEIDY TATI QUICENO TELLEZ",
      "direccion": "Calle: CL 7 Placa: 14-27 Apto: PI1-102 Com: CAI Div: RVA",
      "ciudad": "CAICEDONIA",
      "nodo": "CACE80",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 4.33081,
      "longitud": -75.82796,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "PDV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "RODAS GIRALDO JHON ALE",
      "codigo_asesor": "94903554",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 149,
      "tiempo_viaje_minutos": 28,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465741185_O_CO_7",
      "external_id": "1110530540",
      "tecnico": "OSORIO ANTOLINEZ FRANCISCO JAVIER",
      "fecha": "2026-02-26",
      "inicio": "15:12",
      "fin": "16:28",
      "cliente": "CAROLINA GONZALEZ CASTAEDA",
      "direccion": "Calle: LOS ALPES Placa: MZF-C15 Apto: CASA Com: IBA Div: RCE",
      "ciudad": "IBAGUE",
      "nodo": "RUE",
      "zona": 506561,
      "regional": "RCE",
      "latitud": 4.45691,
      "longitud": -75.20331,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "RODRIGUEZ HERRERA ANDR",
      "codigo_asesor": "65786685",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 76,
      "tiempo_viaje_minutos": 21,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465732955_O_CO_7",
      "external_id": "1075321497",
      "tecnico": "MIGUEL ANGEL VILLARREAL MEDINA",
      "fecha": "2026-02-26",
      "inicio": "12:18",
      "fin": "12:57",
      "cliente": "JUAN SALVA ARDILA MALPICA",
      "direccion": "Calle: CL 3A Placa: 19-60 Apto: PI1-103 Com: NEI Div: RCE",
      "ciudad": "NEIVA",
      "nodo": "N1Q1",
      "zona": 506564,
      "regional": "RCE",
      "latitud": 2.92569,
      "longitud": -75.27438,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "SALINAS MORENO MARIA F",
      "codigo_asesor": "89601755",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 39,
      "tiempo_viaje_minutos": 40,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465829823_O_CO_761",
      "external_id": "10347366",
      "tecnico": "TRUQUE RIVERA GERSAIN ANDRES",
      "fecha": "2026-02-28",
      "inicio": "11:00",
      "fin": "11:28",
      "cliente": "PAOLA ANDR MARIN BEJARANO",
      "direccion": "Calle: CR 41C Placa: 17-08 Apto: PISO2 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "XO132C",
      "zona": 508584,
      "regional": "RVA",
      "latitud": 3.41542,
      "longitud": -76.52345,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "SANCHEZ CASTILLO MARY",
      "codigo_asesor": "59447282",
      "confirmacion": "si",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 28,
      "tiempo_viaje_minutos": 37,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466211133_O_CO_761",
      "external_id": "1087130962",
      "tecnico": "JUAN CARLOS ORDOEZ SILVA",
      "fecha": "2026-03-06",
      "inicio": "15:21",
      "fin": "15:59",
      "cliente": "JHON DANNY MELO",
      "direccion": "Calle: CL 36 Placa: 34-58 Apto:  PI3-301 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "CNCLG4",
      "zona": 508582,
      "regional": "RVA",
      "latitud": 3.4205,
      "longitud": -76.50734,
      "aliado": "TABASCO OC, LLC. SUCURSAL COLOMBIA",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "SANCHEZ CUENO LUZ DAR",
      "codigo_asesor": "59165444",
      "confirmacion": "si",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "EN INCUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "22",
      "duracion_minutos": 38,
      "tiempo_viaje_minutos": 57,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464730992_O_CO_761",
      "external_id": "1107085335",
      "tecnico": "EYVAR ANDRES SUAREZ VELASCO",
      "fecha": "2026-02-11",
      "inicio": "14:07",
      "fin": "14:28",
      "cliente": "CONSTANZA OSPINA SEPULVEDA",
      "direccion": "Calle: CL 33F Placa: 20-28 Apto: PISO2 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "XK1277",
      "zona": 508582,
      "regional": "RVA",
      "latitud": 3.43874,
      "longitud": -76.50871,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "SERNA VELEZ ERNESTO",
      "codigo_asesor": "7554141",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 21,
      "tiempo_viaje_minutos": 35,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465763846_O_CO_761",
      "external_id": "1143995495",
      "tecnico": "BRAYAN ESTIVEN ARAGN KLINGER",
      "fecha": "2026-02-27",
      "inicio": "07:07",
      "fin": "10:21",
      "cliente": "JONATHAN PIEDRAHITAA BERNAL",
      "direccion": "Calle: CR 1F TORRE A Placa: 58-50 Apto: 106 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "XH0914",
      "zona": 508582,
      "regional": "RVA",
      "latitud": 3.47069,
      "longitud": -76.49701,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "PDV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "SOELIA DE JESUS MONSAL",
      "codigo_asesor": "31231151",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 194,
      "tiempo_viaje_minutos": 21,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "464898824_O_CO_7",
      "external_id": "1070614715",
      "tecnico": "MIGUEL ANGEL RODRIGUEZ ORTIZ",
      "fecha": "2026-02-17",
      "inicio": "16:52",
      "fin": "18:48",
      "cliente": "JOSE ALBER CAICEDO",
      "direccion": "Calle: VILLA LUCIA Placa: MZD-C86 Apto:  PI1-101 Com: FLA Div: RCE",
      "ciudad": "FLANDES",
      "nodo": "VLK3F",
      "zona": 506561,
      "regional": "RCE",
      "latitud": 4.27201,
      "longitud": -74.83092,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "SUAREZ RIVERA PAOLA AN",
      "codigo_asesor": "65820708",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "EN INCUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "78",
      "duracion_minutos": 116,
      "tiempo_viaje_minutos": 29,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "464898824_O_CO_7",
      "external_id": "1070598482",
      "tecnico": "OSCAR DOREL MORENO ARENAS",
      "fecha": "2026-02-16",
      "inicio": "07:46",
      "fin": "09:24",
      "cliente": "JOSE ALBER CAICEDO MSRTINEZ",
      "direccion": "Calle: VILLA LUCIA Placa: MZD-C86 Apto: PI1-101 Com: FLA Div: RCE",
      "ciudad": "FLANDES",
      "nodo": "VLK3F",
      "zona": 506561,
      "regional": "RCE",
      "latitud": 4.27201,
      "longitud": -74.83092,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "AGENTES",
      "canal2": "CALLE",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "SUAREZ RIVERA PAOLA AN",
      "codigo_asesor": "65820708",
      "confirmacion": "si",
      "confir_resultado": "NO CONTACTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 98,
      "tiempo_viaje_minutos": 2,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "464607985_O_CO_12",
      "external_id": "1070614715",
      "tecnico": "MIGUEL ANGEL RODRIGUEZ ORTIZ",
      "fecha": "2026-02-10",
      "inicio": "15:06",
      "fin": "15:42",
      "cliente": "KEVIN ANDR GERENA GALINDO",
      "direccion": "Calle: CL 11A Placa: 13-29 Apto: PI1-102 Com: ESP Div: RCE",
      "ciudad": "ESPINAL",
      "nodo": "ESZ",
      "zona": 506561,
      "regional": "RCE",
      "latitud": 4.14312,
      "longitud": -74.88407,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "Pymes",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Pymes",
      "asesor": "TORRES JIMENEZ KATHERI",
      "codigo_asesor": "23895362",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 36,
      "tiempo_viaje_minutos": 36,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466421650_O_CO_761",
      "external_id": "1002958746",
      "tecnico": "RICHAR ALIRIO PEA ZUIGA",
      "fecha": "2026-03-09",
      "inicio": "14:14",
      "fin": "15:11",
      "cliente": "MARIA CLAR SALAZAR YUTERSONKE",
      "direccion": "Calle: CR 9NORTE Placa: 14-08 Apto: PI1-101 Com: POP Div: RVA",
      "ciudad": "POPAYAN",
      "nodo": "OBFV69",
      "zona": 507572,
      "regional": "RVA",
      "latitud": 2.45355,
      "longitud": -76.6008,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK OUT BOUND",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "TORRES PAEZ LAURA SOFI",
      "codigo_asesor": "11201758",
      "confirmacion": "no",
      "confir_resultado": "",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 57,
      "tiempo_viaje_minutos": 49,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": ""
    },
    {
      "orden": "465118099_O_CO_12",
      "external_id": "16897444",
      "tecnico": "ZAMBRANO ALEXANDER MUNOZ",
      "fecha": "2026-02-20",
      "inicio": "11:44",
      "fin": "12:03",
      "cliente": "GLORIA CEC LLANO HENAO",
      "direccion": "Calle: CL 37A Placa: 27-58 Apto: PORTERIA Com: PAL Div: RVA",
      "ciudad": "PALMIRA",
      "nodo": "C96",
      "zona": 507578,
      "regional": "RVA",
      "latitud": 3.53424,
      "longitud": -76.29739,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "Pymes",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Pymes",
      "asesor": "VELANDIA MORENO ANGIE",
      "codigo_asesor": "92780057",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 72,
      "sla_cumplimiento": "0",
      "duracion_minutos": 19,
      "tiempo_viaje_minutos": 30,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466225497_O_CO_761",
      "external_id": "1047496373",
      "tecnico": "LAFISAID JIMENEZ OJEDA",
      "fecha": "2026-03-06",
      "inicio": "07:58",
      "fin": "11:09",
      "cliente": "DEICY YINE CARDOZO LOZANO",
      "direccion": "Calle: CL 20A Placa: 14-125 Apto: PI1-101 Com: CAN Div: RVA",
      "ciudad": "CANDELARIA",
      "nodo": "OCDIQB",
      "zona": 507578,
      "regional": "RVA",
      "latitud": null,
      "longitud": null,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "TELEFONICO VENTA",
      "canal2": "TMK IN BOUND",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "YESSICA ALEJANDRA AYA",
      "codigo_asesor": "26293729",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 191,
      "tiempo_viaje_minutos": 11,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "466078238_O_CO_7",
      "external_id": "1000780290",
      "tecnico": "JOSE FERNANDO GUTIERREZ CONTRERAS",
      "fecha": "2026-03-04",
      "inicio": "14:32",
      "fin": "15:28",
      "cliente": "YUSSI PAOL PALOMINO",
      "direccion": "Calle: CR 35 Placa: 38-12 Apto: PI3-301 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "1LP",
      "zona": 508582,
      "regional": "RVA",
      "latitud": 3.41942,
      "longitud": -76.50607,
      "aliado": "CICSA COLOMBIA S.A.",
      "canal": "AGENTES",
      "canal2": "EYN",
      "tipo_red": "Masivo Bidireccional",
      "tipo_actividad": "Instalaciones",
      "subtipo_orden": "Instalacion Empaquetada Bi",
      "asesor": "ZULUAGA FAJARDO LOREN",
      "codigo_asesor": "43991801",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 56,
      "tiempo_viaje_minutos": 30,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465218191_O_CO_761",
      "external_id": "1005831497",
      "tecnico": "SARA LEYDI ORTIZ OJEDA",
      "fecha": "2026-02-23",
      "inicio": "07:08",
      "fin": "08:25",
      "cliente": "VALERIA ESCOBAR",
      "direccion": "Calle: CL 75 Placa: 7BIS-83 Apto:  PI1-102 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "OBF273",
      "zona": 508582,
      "regional": "RVA",
      "latitud": null,
      "longitud": null,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "ZUNIGA RIVERA ANGELICA",
      "codigo_asesor": "44152270",
      "confirmacion": "si",
      "confir_resultado": "CONFIRMADO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 1,
      "estado_sla": "NODATA",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 77,
      "tiempo_viaje_minutos": 19,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    },
    {
      "orden": "465218191_O_CO_761",
      "external_id": "1042849412",
      "tecnico": "HAAHALI HABID MIER DE LA HOZ",
      "fecha": "2026-02-21",
      "inicio": "14:16",
      "fin": "16:02",
      "cliente": "VALERIA ESCOBAR",
      "direccion": "Calle: CL 75 Placa: 7BIS-83 Apto: PI1-102 Com: CAL Div: RVA",
      "ciudad": "CALI",
      "nodo": "OBF273",
      "zona": 508582,
      "regional": "RVA",
      "latitud": null,
      "longitud": null,
      "aliado": "CONECTAR TV S.A.S.",
      "canal": "CAV",
      "canal2": "CAV",
      "tipo_red": "FTTH",
      "tipo_actividad": "INSTALACIONES FTTH",
      "subtipo_orden": "Instalacion FTTH_",
      "asesor": "ZUNIGA RIVERA ANGELICA",
      "codigo_asesor": "44152270",
      "confirmacion": "si",
      "confir_resultado": "ADELANTO",
      "despac_causa": "Validación razon",
      "despac_gestion": "Razon validada",
      "num_reprogramaciones": 0,
      "estado_sla": "EN CUMPLIMIENTO",
      "sla_horas": 36,
      "sla_cumplimiento": "0",
      "duracion_minutos": 106,
      "tiempo_viaje_minutos": 18,
      "razon": "UNIDAD POSIBLE FRAUDE",
      "estado": "No completado",
      "persona_confirma": "Gestion IVR"
    }
  ],
  "total_casos": 74,
  "total_registros": 74,
  "confirmados": 41,
  "tasa_confirmacion": 55.4,
  "no_confirmados": 33,
  "en_cumplimiento_sla": 52,
  "tasa_cumplimiento_sla": 70.3,
  "en_incumplimiento_sla": 10,
  "con_reprogramaciones": 22,
  "tasa_reprogramacion": 29.7,
  "sin_reprogramaciones": 52,
  "aliados": {
    "CONECTAR TV S.A.S.": 39,
    "TABASCO OC, LLC. SUCURSAL COLOMBIA": 22,
    "CICSA COLOMBIA S.A.": 13
  },
  "companias": {
    "CONECTAR TV S.A.S.": 39,
    "TABASCO OC, LLC. SUCURSAL COLOMBIA": 22,
    "CICSA COLOMBIA S.A.": 13
  },
  "canal_principal": {
    "AGENTES": 36,
    "TELEFONICO VENTA": 20,
    "CAV": 15,
    "DIGITAL": 2,
    "TELEFONICO SERVICIO": 1
  },
  "canal_secundario": {
    "PDV": 7,
    "TMK OUT BOUND": 15,
    "CALLE": 28,
    "CAV": 15,
    "ECOMMERCE ASISTIDO": 2,
    "SAC": 1,
    "TMK IN BOUND": 5,
    "EYN": 1
  },
  "ciudades": {
    "PALMIRA": 9,
    "POPAYAN": 10,
    "CALI": 20,
    "NEIVA": 6,
    "BUGA": 2,
    "FLANDES": 5,
    "CARTAGO": 5,
    "FLORIDA": 1,
    "SEVILLA": 2,
    "PASTO": 4,
    "ESPINAL": 2,
    "FLORENCIA": 2,
    "CANDELARIA": 2,
    "IPIALES": 2,
    "CAICEDONIA": 1,
    "IBAGUE": 1
  },
  "tipo_red": {
    "Masivo Bidireccional": 41,
    "FTTH": 29,
    "Pymes": 4
  },
  "asesores": {
    "ANDREA CATALINA DE LA": 1,
    "ANDRES MAURICIO MONTER": 2,
    "ANGEL DUBAN MEDINA GUE": 1,
    "ARDILA VAZQUEZ ALIX AL": 1,
    "ARLEX ADEY PALACIOS LO": 2,
    "AVILA ROMERO NILSE DIO": 1,
    "BARRERA RODRIGUEZ MAN": 1,
    "BOLIVAR PULGARIN YESSI": 1,
    "BUITRAGO GIRALDO VALEN": 1,
    "CARDONA ZAPATA LUZ ARG": 1,
    "CASTILLO GARCIA JOHANN": 1,
    "CHITOYEISON EDUARDO": 1,
    "DIEGO ANDRES SOTO MART": 1,
    "EDWIN ANDRES HERNANDEZ": 1,
    "ERIKA PAOLA ESPINOSA V": 1,
    "ESTEBAN CALLE CHAVARRI": 1,
    "FAVIO VEGA DOCTOR": 1,
    "FLOREZ CARLOS ARTURO": 1,
    "GOMEZ VILLANUEVA HAROL": 1,
    "GONZALEZ CESPEDES JUAN": 1,
    "GUZMAN VELA SEBASTIAN": 2,
    "HAIDER DAVID MEDINA CA": 1,
    "HERNANDEZ PERALTA JONA": 1,
    "HOMEN BURBANO CLAUDIA": 1,
    "JAIR PALACIO NIEVES": 1,
    "JANIRIA BERNAL JIMENEZ": 1,
    "JEFERSON RODRIGUEZ ROM": 1,
    "JHOANA PAOLA VARON BE": 1,
    "JHONN JAIRO ORTEGA PER": 1,
    "JOAN MAURICIO GARCIA Q": 1,
    "JOHANA ROSERO PERENGUE": 3,
    "JOSE LUIS OLARTE NOREN": 1,
    "KATHERIN DAZA IBARRA": 1,
    "LEON RIANO JOHAN SAMUE": 1,
    "LUIS ADOLFO VALENCIA R": 1,
    "LUIS EDUARDO VILLAFANE": 2,
    "MAESTRE BIRRIEL ELISA": 2,
    "MARIA CAROLINA PENA RA": 1,
    "MIGUEL ANGEL LOPEZ ARE": 1,
    "MILLER SANTACRUZ NARVA": 1,
    "MINGAN PERALTA ESTEFAN": 1,
    "MORALES BRITNEY DAYAN": 1,
    "MORALES HERNANDEZ MONI": 1,
    "MOSQUERA AREVALO JOHN": 1,
    "ONATE MEJIA JESUS ALEX": 1,
    "OSCAR LEONARDO PARRADO": 2,
    "PENA MORENO DANIEL FEL": 1,
    "POLANIA MONTERO LUISA": 1,
    "POTES BEDOYA LUZ AIDEE": 1,
    "PULIDO RODRIGUEZ DANIE": 1,
    "RODAS GIRALDO JHON ALE": 1,
    "RODRIGUEZ HERRERA ANDR": 1,
    "SALINAS MORENO MARIA F": 1,
    "SANCHEZ CASTILLO MARY": 1,
    "SANCHEZ CUENO LUZ DAR": 1,
    "SERNA VELEZ ERNESTO": 1,
    "SOELIA DE JESUS MONSAL": 1,
    "SUAREZ RIVERA PAOLA AN": 2,
    "TORRES JIMENEZ KATHERI": 1,
    "TORRES PAEZ LAURA SOFI": 1,
    "VELANDIA MORENO ANGIE": 1,
    "YESSICA ALEJANDRA AYA": 1,
    "ZULUAGA FAJARDO LOREN": 1,
    "ZUNIGA RIVERA ANGELICA": 2
  },
  "tecnicos": {
    "BRAYAN STEVEN GUERRON TORRES": 1,
    "DIDIER ENRIQUE PEREZ SARRIA": 2,
    "YEINEY ALEXIS RIVERA MENESES": 1,
    "JORGE LEONARDO REYES CASTILLO": 1,
    "MILTON ANDRES AGUDELO RAMIREZ": 2,
    "JESUS ALFREDO RODRIGUEZ MORA": 3,
    "ANDRES FELIPE VICUA GARCIA": 1,
    "RICHAR ALIRIO PEA ZUIGA": 2,
    "CARLOS ADRIAN ROJAS CRUZ": 1,
    "JOSE ADOLFO TORRES TORRES": 2,
    "IJAJI SAMBONI EYSON FERNANDO": 1,
    "WILNER YESID RIASCOS MOSQUERA": 1,
    "EVILEY ALBERTO SERNA OROZCO": 1,
    "DIEGO FERNANDO LOPEZ ALTAMIRANO": 1,
    "JAIME IBARGUEN ANGULO": 1,
    "JORGE LUIS HENAO SALAZAR": 2,
    "JHEFRY GABRIEL DUQUE MACA": 1,
    "JAVIER DELGADO CEDEO": 2,
    "ORTIZ SALAZAR JEAN CARLOS": 1,
    "HERBIN ARLEY MURILLO MOSQUERA": 1,
    "JHON JAIRO GARCIA TORRES": 1,
    "CARLOS FABIAN LEIVA CRUZ": 2,
    "JEFERSON ANDRES MORALES CIFUENTES": 1,
    "ALEX JOVANNY VICTORIA PECHENE": 2,
    "ARY ROBERTO GOMEZ GUAMPE": 1,
    "JAIME EDWIN CAMPAA": 1,
    "MONCAYO EDDIER MORA": 1,
    "DILERMANDO ULCUE ACHIPIZ": 1,
    "ANGEL HERRERA GUZMAN LUIS": 1,
    "HECTOR VICENTE MARQUEZ BARRETO": 1,
    "ZAMBRANO ALEXANDER MUNOZ": 2,
    "MERA GIOVANNY TORRES": 2,
    "JOEL ANDREY QUIROGA SANCHEZ": 1,
    "JOHNNY RODRIGO DE LA CRUZ DIAZ": 1,
    "JANYER VALENZUELA GARZON": 1,
    "SANTIAGO ACUA LOSADA": 1,
    "FREDDY AVILES SANCHEZ": 1,
    "OSCAR ALONSO MONTOYA MANRIQUE": 1,
    "SEBASTIAN GUTIERREZ MORALES": 1,
    "ANDERSON ALDAIR GUERRERO CHANA": 1,
    "ANDERSON ELESVAN VALENCIA AGUIRRE": 1,
    "CENEN LEONARDO ESCOBEDO IDROBO": 1,
    "JORGE ALEXANDER LOPEZ ORTEGA": 1,
    "BRAYAN ANDRES PEA ZUIGA": 2,
    "MARC ANTONY INAGAN PINCHAO": 2,
    "JHON JAIRO MAMIAN VELASCO": 1,
    "CRISTIAN DANILO URRESTY ORDOEZ": 1,
    "OSORIO ANTOLINEZ FRANCISCO JAVIER": 1,
    "MIGUEL ANGEL VILLARREAL MEDINA": 1,
    "TRUQUE RIVERA GERSAIN ANDRES": 1,
    "JUAN CARLOS ORDOEZ SILVA": 1,
    "EYVAR ANDRES SUAREZ VELASCO": 1,
    "BRAYAN ESTIVEN ARAGN KLINGER": 1,
    "MIGUEL ANGEL RODRIGUEZ ORTIZ": 2,
    "OSCAR DOREL MORENO ARENAS": 1,
    "LAFISAID JIMENEZ OJEDA": 1,
    "JOSE FERNANDO GUTIERREZ CONTRERAS": 1,
    "SARA LEYDI ORTIZ OJEDA": 1,
    "HAAHALI HABID MIER DE LA HOZ": 1
  },
  "nodos": {
    "PBU": 1,
    "CB3": 2,
    "ASE2F": 1,
    "PMS1": 1,
    "D2B": 1,
    "QTN": 1,
    "OBFL10": 1,
    "4SN": 1,
    "CT03": 1,
    "AIA": 1,
    "OBFL08": 1,
    "OBFM58": 1,
    "OBFO39": 1,
    "F4M1": 1,
    "L3S": 1,
    "CTDE15": 1,
    "CPE1": 1,
    "TM1": 1,
    "KAN2F": 1,
    "QTO3F": 1,
    "B2Q3F": 1,
    "SEVIG7": 2,
    "NVE1": 1,
    "4SP": 2,
    "VGE": 1,
    "TOG3B": 1,
    "UVU": 1,
    "ESV": 1,
    "LMV1": 1,
    "OS3": 1,
    "PAK": 1,
    "JOS": 1,
    "OS4": 1,
    "HPI": 1,
    "OBFJ39": 1,
    "XX1": 1,
    "OS2": 1,
    "SPU1": 2,
    "CT13": 2,
    "MTN1": 1,
    "MQ2": 1,
    "OBFX36": 1,
    "OCDIQB": 2,
    "OCDJOQ": 1,
    "CTCG93": 1,
    "DIA": 1,
    "OBFO24": 1,
    "IPIPE9": 2,
    "JSE2D": 1,
    "1LT": 1,
    "NBN1": 1,
    "PYBF78": 1,
    "CACE80": 1,
    "RUE": 1,
    "N1Q1": 1,
    "XO132C": 1,
    "CNCLG4": 1,
    "XK1277": 1,
    "XH0914": 1,
    "VLK3F": 2,
    "ESZ": 1,
    "OBFV69": 1,
    "C96": 1,
    "1LP": 1,
    "OBF273": 2
  },
  "zonas": {
    "507578": 22,
    "507572": 10,
    "508584": 9,
    "506564": 8,
    "506561": 8,
    "508582": 11,
    "507573": 6
  },
  "regionales": {
    "RVA": 53,
    "RCE": 16,
    "REC": 5
  },
  "confir_resultados": {
    "CONFIRMADO": 23,
    "": 28,
    "NO CONTACTO": 11,
    "ADELANTO": 11,
    "REPROGRAMADA": 1
  },
  "estados_sla": {
    "EN CUMPLIMIENTO": 52,
    "EN INCUMPLIMIENTO": 10,
    "NODATA": 12
  },
  "subtipos_orden": {
    "Instalacion Basica Bi": 14,
    "Instalacion Empaquetada Bi": 27,
    "Instalacion FTTH_": 28,
    "Instalacion Pymes": 4,
    "BROWNFIELD": 1
  }
};